export type FounderProfile = {
  name: string;
  title: string;
  biz: string;
  city: string;
  area: string;
  niche: string;
  sector: string;
  story: string;
  img: string;
  bizImg: string;
  tags: string[];
  network: string;
  verified: boolean;
  featured: boolean;
};

export const FOUNDERS: FounderProfile[] = [
  { name: "Adeola Mensah", title: "Award-winning Florist & Event Stylist", biz: "Bloom & Thread", city: "Manchester", area: "Northern Quarter", niche: "Floral Design · Events", sector: "Creative", story: "Adeola left a corporate HR job in 2019 to follow her passion. Bloom & Thread now styles 80+ weddings and corporate events a year across the North West. Hidden gem: she teaches monthly wreath-making workshops that sell out in hours.", img: "https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=500&q=80&fit=crop&crop=face,top", bizImg: "https://images.unsplash.com/photo-1487530811015-780a6d1717b2?w=500&q=80&fit=crop", tags: ["Weddings", "Events", "Workshops"], network: "Photographers, caterers, venues", verified: true, featured: true },
  { name: "Reuben Osei", title: "Master Barber & Grooming Coach", biz: "The Cut Standard", city: "Manchester", area: "Moss Side", niche: "Barbering · Men's Grooming", sector: "Wellness", story: "Reuben trained under two of the UK's top barbers before opening The Cut Standard at 24. He's built a loyal community of 600+ regulars — and a side business training the next generation of barbers. His courses are cheaper than any college.", img: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=500&q=80&fit=crop&crop=face,top", bizImg: "https://images.unsplash.com/photo-1622286342621-4bd786c2447c?w=500&q=80&fit=crop", tags: ["Barbering", "Training", "Grooming"], network: "Fashion brands, content creators", verified: true, featured: true },
  { name: "Suki Patel", title: "Independent Restaurateur & Spice Educator", biz: "Saffron Table", city: "Manchester", area: "Didsbury", niche: "South Asian Cuisine · Food Education", sector: "Hospitality", story: "Suki's restaurant Saffron Table is a 48-seat gem in Didsbury that's been on every Manchester foodie's list since 2021. She also hosts private 'cook the culture' evenings that TKBees members love.", img: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=500&q=80&fit=crop&crop=face,top", bizImg: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=500&q=80&fit=crop", tags: ["Restaurant", "Cooking Classes", "Spices"], network: "Food photographers, delivery partners", verified: true, featured: false },
  { name: "Marcus Brodie", title: "Structural Engineer turned Woodcraft Maker", biz: "Brodie & Grain", city: "Manchester", area: "Ancoats", niche: "Bespoke Furniture · Interior Craft", sector: "Craft & Design", story: "Marcus walked away from a £70K engineering salary to build furniture in a converted railway arch in Ancoats. His 18-week order backlog says everything. He sources all timber from certified UK forests. You'll only find him if you know where to look.", img: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=500&q=80&fit=crop&crop=face,top", bizImg: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=500&q=80&fit=crop", tags: ["Furniture", "Woodcraft", "Bespoke"], network: "Interior designers, architects, property developers", verified: true, featured: false },
  { name: "Yewande Obi", title: "Textile Artist & Fashion Upcycler", biz: "Thread Reborn", city: "Manchester", area: "Hulme", niche: "Sustainable Fashion · Textile Art", sector: "Fashion", story: "Yewande turns discarded clothing into gallery-worthy wearable art. She's stocked in two Afflecks stores, shown at Manchester Art Gallery, and is quietly building one of the city's most ethical fashion labels — with zero external funding.", img: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=500&q=80&fit=crop&crop=face,top", bizImg: "https://images.unsplash.com/photo-1558769132-cb1aea458c5e?w=500&q=80&fit=crop", tags: ["Sustainable Fashion", "Art", "Upcycling"], network: "Galleries, boutiques, sustainability journalists", verified: true, featured: true },
  { name: "Leon Baptiste", title: "Independent Financial Coach", biz: "Wealth on Purpose", city: "London", area: "Brixton", niche: "Financial Literacy · Wealth Building", sector: "Finance", story: "Leon grew up on a council estate and made his first property investment at 21. He now coaches 300+ clients — mostly young professionals who've never been taught how money works. His Saturday sessions in Brixton have a 3-month waiting list.", img: "https://images.unsplash.com/photo-1530268729831-4b0b9e170218?w=500&q=80&fit=crop&crop=face,top", bizImg: "https://images.unsplash.com/photo-1553729459-efe14ef6055d?w=500&q=80&fit=crop", tags: ["Finance", "Coaching", "Property"], network: "Accountants, property investors, legal advisors", verified: true, featured: false },
  { name: "Amara Diallo", title: "Wellness Practitioner & Retreat Host", biz: "Still & Strong", city: "Birmingham", area: "Moseley", niche: "Wellbeing · Yoga · Retreats", sector: "Wellness", story: "Amara runs monthly urban retreats out of a converted Victorian terrace in Moseley — yoga, breathwork, sound baths and group therapy for professionals who are quietly burning out. Her 6-week programme has a 100% referral rate.", img: "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=500&q=80&fit=crop&crop=face,top", bizImg: "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=500&q=80&fit=crop", tags: ["Wellness", "Yoga", "Retreats"], network: "Nutritionists, therapists, hotels", verified: true, featured: false },
  { name: "Joel Nkrumah", title: "Urban Farmer & Food Justice Activist", biz: "Green Roots MCR", city: "Manchester", area: "Wythenshawe", niche: "Urban Farming · Community Food", sector: "Social Enterprise", story: "Joel turned three derelict plots in Wythenshawe into productive urban farms supplying 14 local families with fresh veg every week. He's a TED speaker and consults for the Greater Manchester Combined Authority on food poverty.", img: "https://images.unsplash.com/photo-1506277886164-e25aa3f4ef7f?w=500&q=80&fit=crop&crop=face,top", bizImg: "https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=500&q=80&fit=crop", tags: ["Urban Farming", "Food Justice", "Social Enterprise"], network: "Supermarkets, councils, schools", verified: true, featured: true },
  { name: "Nadia Kovalenko", title: "Illustration Studio Owner & Art Director", biz: "Studio Kova", city: "Manchester", area: "Castlefield", niche: "Editorial Illustration · Brand Art", sector: "Creative", story: "Nadia left Ukraine at 18, won a scholarship to MMU, and built Studio Kova from her bedroom at 22. She now has commissions from The Guardian, Penguin Books and three FTSE 100 companies — and teaches illustration bootcamps every Sunday.", img: "https://images.unsplash.com/photo-1502685104226-ee32379fefbe?w=500&q=80&fit=crop&crop=face,top", bizImg: "https://images.unsplash.com/photo-1561070791-2526d30994b5?w=500&q=80&fit=crop", tags: ["Illustration", "Brand Art", "Teaching"], network: "Publishers, agencies, art directors", verified: true, featured: false },
  { name: "Kwabena Asante", title: "Sound Engineer & Music Producer", biz: "Frequency Lab", city: "Manchester", area: "Salford", niche: "Music Production · Audio Engineering", sector: "Music & Audio", story: "Kwabena's studio in Salford has produced three UK top-40 tracks and a BAFTA-nominated documentary score — squeezed into a Victorian railway arch with a handpainted sign. He mentors 12 young producers for free every Saturday morning.", img: "https://images.unsplash.com/photo-1531891437562-4301cf35b7e4?w=500&q=80&fit=crop&crop=face,top", bizImg: "https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?w=500&q=80&fit=crop", tags: ["Music", "Audio", "Production"], network: "Labels, filmmakers, podcasters", verified: true, featured: false },
  { name: "Fatima Al-Rashid", title: "Architect & Community Housing Advocate", biz: "Open Ground Studio", city: "Manchester", area: "Longsight", niche: "Architecture · Social Housing Design", sector: "Architecture", story: "Fatima's studio designs affordable housing schemes with the residents, not for them. She's completed 6 social housing projects across Greater Manchester and is the only architect on the city council's housing advisory board.", img: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=500&q=80&fit=crop&crop=face,top", bizImg: "https://images.unsplash.com/photo-1486325212027-8081e485255e?w=500&q=80&fit=crop", tags: ["Architecture", "Social Housing", "Community"], network: "Councils, developers, planners", verified: true, featured: false },
  { name: "David Okoye", title: "Independent Watchmaker", biz: "Okoye Horology", city: "Leeds", area: "Chapel Allerton", niche: "Watchmaking · Luxury Repair", sector: "Craft", story: "David is one of fewer than 400 fully trained watchmakers left in the UK. He restores watches from a tiny workshop above a deli in Chapel Allerton — clients ship pieces from Europe and the US. His apprenticeship programme is now accepting applications.", img: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=500&q=80&fit=crop&crop=face,top", bizImg: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=500&q=80&fit=crop", tags: ["Watchmaking", "Luxury", "Craft"], network: "Jewellers, collectors, luxury brands", verified: true, featured: false },
];

export const FOUNDER_SECTORS = ["All", "Creative", "Wellness", "Hospitality", "Finance", "Fashion", "Social Enterprise", "Music & Audio", "Architecture", "Craft & Design", "Craft"];
export const FOUNDER_CITIES = ["All Cities", "Manchester", "London", "Birmingham", "Leeds"];
export const FOUNDER_NEIGHBOURHOODS = ["All", "Northern Quarter", "Ancoats", "Moss Side", "Hulme", "Didsbury", "Castlefield", "Wythenshawe", "Salford", "Longsight"];
export const SECTOR_BADGES = [
  { e: "🌿", s: "Wellness", n: "47", c: "#C6F432" },
  { e: "🎨", s: "Creative", n: "84", c: "#F5A524" },
  { e: "🍽️", s: "Hospitality", n: "63", c: "#FF6B6B" },
  { e: "💰", s: "Finance", n: "38", c: "#1E1B4B" },
  { e: "👗", s: "Fashion", n: "52", c: "#F5A524" },
  { e: "🔨", s: "Craft & Design", n: "41", c: "#C6F432" },
  { e: "🎵", s: "Music & Audio", n: "29", c: "#FF6B6B" },
  { e: "🏗️", s: "Architecture", n: "22", c: "#1E1B4B" },
];
